export const ADD_MATCH = 'ADD_MATCH';
export const UPDATE_MATCH = 'UPDATE_MATCH';

export const ADD_SET = 'ADD_SET';
export const ADD_STAT = 'ADD_STAT';
export const UNDO_LAST_STAT = 'UNDO_LAST_STAT';
export const TOGGLE_ADJUSTMENT_LAST_STAT = 'TOGGLE_ADJUSTMENT_LAST_STAT';
export const UPDATE_STATS_ORDER = 'UPDATE_STATS_ORDER';

export const LOCAL_STORAGE_KEY = 'STREAMLINED_STATE';
