const numberAlternates = [
  ['0', 'zero', 'xero'],
  ['1', 'one', 'won', '1:00', 'juan', 'when'],
  ['2', 'two', 'to'],
  [
    '3',
    'three',
    'tree',
    'thee',
    'free',
    'in three',
    'and 3',
    'and three',
    'in 3',
  ],
  ['4', 'four', 'for', 'or', 'poor'],
  ['5', 'five', '5:00'],
  ['6', 'six'],
  ['7', 'seven'],
  ['8', 'eight', 'date', 'eat', 'each'],
  ['9', 'nine'],
  ['10', 'ten'],
  ['11', 'eleven'],
  ['12', 'twelve'],
  ['13', 'thirteen'],
  ['14', 'fourteen'],
  ['15', 'fifteen'],
  ['16', 'sixteen'],
  ['17', 'seventeen'],
  ['18', 'eighteen'],
  ['19', 'nineteen'],
  ['20', 'twenty'],
];

export default numberAlternates;
